dataset_root : ./MSRS
dataset_name : MSRS
seed : 3407
have_seg_label : False
project_name : SFDFusion
exp_name : model-MSRS_ChannelFixed
resume : ~
img_size : 320

log_level : INFO
wandb_mode: online
#5e4032d1bef2be6bef054322cead08c46606c50f
start_epoch : 0
num_epochs : 200
epoch_gap : 200
batch_size : 4
num_workers : 0
lr_i : 5.0e-4
lr_f : 0.1
momentum : 0.937

coeff_content: 1
coeff_ssim: 1
coeff_saliency: 10
coeff_fre: 1
coeff_sf: 0.5
coeff_freq_hf: 7
coeff_enhance: 1